title: Slow But Steady
author: Sara T
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  a blog dedicated to my non-traditional personal + professional journey

# social links
twitter_username: sara_takane # DO NOT include the @ character, or else the build will fail!
github_username:  saratakane # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
